### PR TITLE
Fix/logging

### LINKED ISSUE #31: Logging

### PR DESCRIPTION
**Pull request by nedvin**
Logging proof of concept.

Error logs are sent to Sentry as long as the environment variable SENTRY_DSN is set, otherwise not. This solves the problem of not sending lots of development logs to the cloud.

When running the application locally, logs at level INFO or higher (WARN, ERROR) are printed to STDOUT. If we want to set a lower level we can use a little script (run.sh) that is provided with this PR. Instructions on how to run the script is provided inside it.

closes #31

### CODE REVIEW

File: backend/src/main/java/se/kth/iv1201/recruitmentapplicationgroup5/controller/ApiExceptionHandler.java [hunk 1]
```diff
@@ -55,18 +55,19 @@
...
+		log.debug(e.getMessage());
 		return handleInternalError(e, req);
 	}
 	
 	private ResponseEntity<Object> handleInternalError(Exception e, WebRequest req) {
-		//Log error here instead of System.out
-		System.out.println(e);
-		System.out.println(req);
+		log.debug(e.getMessage());
+		log.debug(e.getStackTrace().toString());
```
Comment (RW90) [inline backend/src/main/java/se/kth/iv1201/recruitmentapplicationgroup5/controller/ApiExceptionHandler.java]: This only prints the pointer to the array of stacks. I recommend changing this line to: 
log.debug(Arrays.toString(e.getStackTrace()).replaceAll(",", "\n"));

For other alternatives, solutions see https://stackoverflow.com/questions/1149703/how-can-i-convert-a-stack-trace-to-a-string

**Review by RW90 — CHANGES_REQUESTED** [review]
One minor change requested, I tried out my suggestion and it worked decently.

**Review by RW90 — APPROVED** [review]

**Review by joaxcar — APPROVED** [review]
